export const featuredTracks = [
    {
        id: "1",
        title: "Hadawatha Parana",
        titleSinhala: "හදවත පාරනා",
        album: "Single",
        year: 2024,
        duration: "4:12",
        genre: "Sinhala Pop",
        coverImage: "/images/music/hadawatha-parana.jpg",
        audioPreview: "/audio/hadawatha-parana-preview.mp3",
        description: "A soulful melody that captures the essence of longing and love, blending traditional Sinhala musical elements with contemporary production.",
        streamingLinks: {
            spotify: "https://open.spotify.com/track/...",
            youtube: "https://youtube.com/watch?v=...",
            appleMusic: "https://music.apple.com/...",
            soundcloud: "https://soundcloud.com/...",
        },
        featured: true,
    },
    {
        id: "2",
        title: "Mage Sitha",
        titleSinhala: "මගේ සිත",
        album: "Reflections",
        year: 2023,
        duration: "3:45",
        genre: "Acoustic",
        coverImage: "/images/music/mage-sitha.jpg",
        audioPreview: "/audio/mage-sitha-preview.mp3",
        description: "An acoustic masterpiece that strips away the layers to reveal raw emotion and the power of the human voice.",
        streamingLinks: {
            spotify: "https://open.spotify.com/track/...",
            youtube: "https://youtube.com/watch?v=...",
            appleMusic: "https://music.apple.com/...",
        },
        featured: true,
    },
    {
        id: "3",
        title: "Raa Wasse",
        titleSinhala: "රා වැස්සේ",
        album: "Night Stories",
        year: 2023,
        duration: "5:01",
        genre: "Cinematic Pop",
        coverImage: "/images/music/raa-wasse.jpg",
        audioPreview: "/audio/raa-wasse-preview.mp3",
        description: "A cinematic journey through the rain-soaked streets of Colombo, where every drop tells a story of memory and hope.",
        streamingLinks: {
            spotify: "https://open.spotify.com/track/...",
            youtube: "https://youtube.com/watch?v=...",
        },
        featured: true,
    },
    {
        id: "4",
        title: "Adaraya Athi",
        titleSinhala: "ආදරය ඇති",
        album: "Single",
        year: 2024,
        duration: "3:58",
        genre: "Contemporary Sinhala",
        coverImage: "/images/music/adaraya-athi.jpg",
        audioPreview: "/audio/adaraya-athi-preview.mp3",
        description: "A contemporary love ballad that bridges generations, speaking to the universal language of the heart.",
        streamingLinks: {
            spotify: "https://open.spotify.com/track/...",
            youtube: "https://youtube.com/watch?v=...",
            appleMusic: "https://music.apple.com/...",
        },
        featured: true,
    },
];

export const collaborations = [
    {
        id: "1",
        collaborator: "Bathiya & Santhush",
        project: "Sanda Eliya",
        type: "Single",
        year: 2024,
        image: "/images/collaborations/bns.jpg",
        description: "A landmark collaboration bringing together three of Sri Lanka's most powerful voices.",
    },
    {
        id: "2",
        collaborator: "Sirasa TV",
        project: "National Music Awards Performance",
        type: "Live Performance",
        year: 2023,
        image: "/images/collaborations/sirasa.jpg",
        description: "A show-stopping performance at Sri Lanka's most prestigious music awards ceremony.",
    },
    {
        id: "3",
        collaborator: "Dilmah Tea",
        project: "Brand Campaign — 'Taste of Ceylon'",
        type: "Brand Campaign",
        year: 2023,
        image: "/images/collaborations/dilmah.jpg",
        description: "Original music composed for Dilmah's international brand campaign celebrating Sri Lankan heritage.",
    },
    {
        id: "4",
        collaborator: "Yohani",
        project: "Manike Remix",
        type: "Single",
        year: 2022,
        image: "/images/collaborations/yohani.jpg",
        description: "A viral collaboration that took the internet by storm, amassing millions of views worldwide.",
    },
    {
        id: "5",
        collaborator: "Derana Film Awards",
        project: "Original Film Score",
        type: "Film",
        year: 2022,
        image: "/images/collaborations/derana.jpg",
        description: "Composing the original score for an award-winning Sinhala feature film.",
    },
    {
        id: "6",
        collaborator: "Red Bull Music",
        project: "Red Bull SoundClash Sri Lanka",
        type: "Live Event",
        year: 2023,
        image: "/images/collaborations/redbull.jpg",
        description: "Headlining Red Bull's premier music event in Colombo, performing to a crowd of 10,000+.",
    },
];

export const galleryImages = [
    { id: "1", src: "/images/gallery/concert-01.jpg", alt: "Chanuka Mora performing at Nelum Pokuna Theatre", aspect: "16:9", event: "Nelum Pokuna Live", year: 2024 },
    { id: "2", src: "/images/gallery/studio-01.jpg", alt: "Recording session at Torana Studios", aspect: "3:4", event: "Studio Session", year: 2024 },
    { id: "3", src: "/images/gallery/portrait-01.jpg", alt: "Chanuka Mora portrait, black and white", aspect: "3:4", event: "Editorial Shoot", year: 2023 },
    { id: "4", src: "/images/gallery/concert-02.jpg", alt: "Audience at live concert in Colombo", aspect: "16:9", event: "Colombo Music Festival", year: 2023 },
    { id: "5", src: "/images/gallery/bts-01.jpg", alt: "Behind the scenes of music video shoot", aspect: "1:1", event: "MV Behind the Scenes", year: 2023 },
    { id: "6", src: "/images/gallery/concert-03.jpg", alt: "Chanuka Mora with acoustic guitar on stage", aspect: "4:3", event: "Unplugged Session", year: 2022 },
    { id: "7", src: "/images/gallery/award-01.jpg", alt: "Receiving Best Male Vocalist award", aspect: "3:4", event: "Music Awards 2023", year: 2023 },
    { id: "8", src: "/images/gallery/studio-02.jpg", alt: "Vocal recording close-up with microphone", aspect: "1:1", event: "Album Recording", year: 2024 },
];

export const artistStats = [
    { label: "Songs Released", value: 50, suffix: "+" },
    { label: "YouTube Views", value: 25, suffix: "M+" },
    { label: "Spotify Streams", value: 10, suffix: "M+" },
    { label: "Live Shows", value: 100, suffix: "+" },
    { label: "Awards", value: 15, suffix: "+" },
    { label: "Collaborations", value: 30, suffix: "+" },
];
